In [2]:
# pip install numpy
# conda install numpy

import numpy as np

In [6]:
print(type([1,2,3]))
print(type((1,2,3)))

print(type(np.array([1,2,3])))
print(type(np.array((1,2,3))))

<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [10]:
np.zeros(5)              # 1 solo numero para un arreglo
np.zeros([5,5])          # 1 lista o tupla para una matriz de n dimensiones
np.zeros((5,5))
np.zeros((2,3,4))
np.zeros((1,2,2,2,2,2))  #6 dimensiones
np.zeros((1000,200))     # 1000 items x 2 posiciones  1000 filas x 200 columnas

array([[[[[[0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.]]],


         [[[0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.]]]],



        [[[[0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.]]],


         [[[0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.]]]]]])

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.arange(5)        # 1 parametros, # de elementos

array([0, 1, 2, 3, 4])

In [18]:
np.arange(4,20)    # [4, 20[

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
np.arange(-12,1)    # [-12, 1[

array([-12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [17]:
np.arange(0,20,2)   # Del [0, 20[ en intervalos de 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
np.arange(0,2.1,0.1) # Del [0, 20[ en intervalos de 0.1

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ])

In [21]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
np.zeros(20).reshape(2,5,2).reshape(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [25]:
len(np.ones(12))  #len devuelve la longitud del arreglo

12

In [24]:
len(np.ones(12).reshape(4,3))

4

In [26]:
np.ones(12).reshape(4,3)        #Cambiamos las dimensiones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.ones(12).reshape(4,3).shape   # Devuelve el número de dimensiones

(4, 3)

In [29]:
np.arange(12).reshape(4,3)[1,2]  # Dev los valores en la posicion del arreglo

5

In [31]:
a = np.array([10,10,10])
b = np.array([5,5,5]) 

In [35]:
a + b   # Suma

array([15, 15, 15])

In [34]:
a - b   # Resta

array([5, 5, 5])

In [36]:
a + 7   # Suma

array([17, 17, 17])

In [37]:
a - 8   # Resta

array([2, 2, 2])

In [38]:
a * b   # Multiplicacion

array([50, 50, 50])

In [39]:
a * 3   # Multiplicacion

array([30, 30, 30])

In [40]:
a / b   # Division

array([2., 2., 2.])

In [41]:
a / 2   # Division

array([5., 5., 5.])

In [42]:
a % b   # Módulo

array([0, 0, 0], dtype=int32)

In [43]:
a % 3   # Módulo

array([1, 1, 1], dtype=int32)

In [45]:
muestra = np.arange(20).reshape(5,2,2)

In [46]:
muestra

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [62]:
respuesta_glucosa = muestra  # Poner condición a el arreglo

In [63]:
respuesta_glucosa

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [50]:
muestra[respuesta_glucosa]  # Filtra valores dentro de un arreglo

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [51]:
# Mayores a 5 glucosa y menores a 14 y que sean pares.

In [77]:
muestra[(respuesta_glucosa > 5) & (respuesta_glucosa < 14) & (respuesta_glucosa % 2 == 0)]

array([ 6,  8, 10, 12])

In [3]:
A = np.arange(4).reshape((2,2))
A

array([[0, 1],
       [2, 3]])

In [4]:
B = np.arange(4,8).reshape((2,2))
B

array([[4, 5],
       [6, 7]])

In [6]:
# Producto Punto
A.dot(B)
np.dot(A,B)

array([[ 6,  7],
       [26, 31]])

In [7]:
B.dot(A)
np.dot(B,A)

array([[10, 19],
       [14, 27]])

In [8]:
# Creación del Arreglo
arreglo_doce = np.arange(12)
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
#Suma de Elementos del Arreglo
arreglo_doce.sum()

66

In [10]:
# Sacar Mínimo del Arreglo
arreglo_doce.min()

0

In [12]:
# Sacar Máximo del Arreglo
arreglo_doce.max()

11

In [13]:
# Seleccionar el rango a Sumar
arreglo_doce[5:].sum()

56

In [14]:
arreglo_doce.reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [15]:
arreglo_doce.reshape(3,2,2).sum()

66

In [16]:
arreglo_doce.reshape(3,2,2).sum(axis = 0)

array([[12, 15],
       [18, 21]])

In [17]:
arreglo_doce.reshape(3,2,2).sum(axis = 1)

array([[ 2,  4],
       [10, 12],
       [18, 20]])

In [18]:
arreglo_doce.reshape(3,2,2).sum(axis = 2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])