In [1]:
import numpy as np

In [3]:
arreglo_grados = np.array([0,30,45,60,90])
arreglo_grados

array([ 0, 30, 45, 60, 90])

In [4]:
arreglo_radianes = arreglo_grados * np.pi /180
arreglo_radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [5]:
np.sin(arreglo_radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [6]:
np.tan(arreglo_radianes)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [11]:
# Devolver un número entero entre 0-11 aleatorio
numero_random = np.random.randint(11) 
numero_random 

10

In [14]:
# Devolver un entero entre dos intervalos
numero_random_negativo = np.random.randint(-9, 2)
numero_random_negativo

-8

In [15]:
# Devolver un número de elemtos entre un intervalo
arreglo_random = np.random.randint(10, 20, 8)
arreglo_random

array([16, 18, 12, 17, 10, 10, 11, 13])

In [16]:
np.random.rand(9)

array([0.62870972, 0.22732696, 0.31414445, 0.87725296, 0.95884161,
       0.73753429, 0.40009087, 0.22083699, 0.09198323])

In [18]:
np.average(arreglo_random)

13.375

In [19]:
np.mean(arreglo_random)

13.375

In [20]:
np.median(arreglo_random)

12.5

In [21]:
arreglo_random.mean()

13.375